apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indexjs-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: indexjs
    spec:
      containers:
      - name: indexjs
        image: jcattanach/node-five
        ports:
        - name: nodejs-port
          containerPort: 8080
