apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: project-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: username/online-repo
        ports:
        - name: nodejs-port
          containerPort: 8080
